apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kwpqjlg05-python-gitops
  description: This is GitOps manifest for kwpqjlg05-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=kwpqjlg05-python
    backstage.io/kubernetes-id: kwpqjlg05-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kwpqjlg05-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kwpqjlg05-python
